#include<stdio.h>
#include<stdlib.h>
//#include"parser.h"
//#include"SymbolTable.h"
//#include"SyntaxAnalysis.h"
#include"codeGeneration.h"
//#include"symbol.h"
// N.SHASHANK - 2009B5A7585P
// D.ADITYA   - 2009B5A7669P

int main(int argc,char *argv[])
{
int printflag=0,parseflag=0,astflag=0,option;
char ans1,ans2,ans3;
printf("-------------------------------------------------------------------------");
printf("\n\nLEVEL  4: Symbol table/ type Checking/ Semantic Rules modules work \n");

printf("  \nPress option for the defined task\n\n1     for  printing the token list generated by the lexer (on the console) \n2     for parsing to verify the syntactic correctness of the input source code and to produce parse tree and print it\n3     for printing the Abstract Syntax Tree \n4     for  printing the Symbol Table \n5     for compiling (front end only) to verify the syntactic and semantic correctness of the input source code and to produce errors\n6     for producing assembly code\n\nEnter Option: ");
scanf("%d",&option);
//printf("\noption=%d\n",option);

//puts("\n1. Do you want to print the token list generated by the lexer? (y/n)");
//scanf(" %c",&ans1);
if(option==1)
	printflag=1;
//printf("Your answer was '%c'",ans1);
//puts("\n2. Do you want to parse to verify the syntactic correctness of the input source code and produce parse tree? (y/n)");
//scanf(" %c",&ans2);
if(option>=2)
	parseflag=1;
//printf("Your answer was '%c'",ans2);
//puts("\n3. Do you want to create the abstract syntax tree and print it? (y/n)");
//scanf(" %c",&ans3);
if(option>=3)
	astflag=1;
//printf("Your answer was '%c'",ans3);

FHashTable t;
HashTable h;
VHashTable v;
VResult r;
Result r1;
RIGHT temp;
TREENODE tr,ast;
t=createFirstFollow(100,"firstandfollow.txt");
v=createVHashTable (100);
createParseTable("grammar.txt",t,v);
tr=parseInputSourceCode(argv[1],v,printflag,parseflag);

if(parseflag==1)
	{
	printParseTree(tr,"parsetree.txt");
	}

ast=createAbstractSyntaxtree(tr);
if(astflag==1)
	{
	printAST(ast,"ast.txt");
	}

printf("\n\n");

//symbol table
SYHashTable syh;
HashTable record;
LHashTable lsym;
SYResult rsy;
LResult lrsy;
FILE *fp4;
char lexeme[100];
char type[100];
char scope[100];
char offset[100];
record=createHashTable (100);
syh=createSYHashTable (100);
lsym=createLHashTable (10);
if(option>=4)
{
symboltable(ast,syh,lsym,record);
if(option==4)
{
fp4=fopen("SymbolTable.txt","r");
printf("\n%50s\n","SymbolTable");
while(fscanf(fp4,"%20s %20s %20s %20s\n",lexeme,type,scope,offset)!=EOF)
printf("%20s %20s %20s %20s\n",lexeme,type,scope,offset);
}
}

/*
if(option>=4)
{
symboltable(ast,syh,lsym,record);
}
if(option==4)
{
fp4=fopen("SymbolTable.txt","r");
printf("\n%50s\n","SymbolTable");
while(fscanf(fp4,"%20s %20s %20s %20s\n",lexeme,type,scope,offset)!=EOF)
printf("%20s %20s %20s %20s\n",lexeme,type,scope,offset);
}
*/
if(option>=5)
syntaxAnalysis(ast,syh,lsym,record);
if(option>=6)
codeGen(ast,syh,lsym,record,argv[2]);//added file name 18th 5pm
return 0;


}


